### ISSUE TITLE
Sample appearing twice

### ISSUE THREAD

**Issue by cpavloud** [emo-bon/observatory-nrmcb-crate#11]
In the https://github.com/emo-bon/observatory-nrmcb-crate/blob/main/logsheets/transformed/sediment_measured.csv, the sample **EMOBON_NRMCB_So_210831_micro_blank** appears twice.
Probably the first one was supposed to be **EMOBON_NRMCB_So_210621_micro_blank**

However, which one was actually sequenced?? The original or the "fake" **EMOBON_NRMCB_So_210831_micro_blank** ?

@melinalou

**Comment by cpavloud** [comment]
There are more values like this.

**Comment by melinalou** [comment]
I don't know

**Comment by cpavloud** [comment]
@melanthia could you contact the providers?

**Comment by melinalou** [comment]
I think that it is corrected by now. Please let me know if not to contact the station.

**Comment by cpavloud** [comment]
Yeap, it seems to be ok.
