### ISSUE TITLE
Wrong temperature values

### ISSUE THREAD

**Issue by cpavloud** [emo-bon/observatory-nrmcb-crate#12]
In https://github.com/emo-bon/observatory-nrmcb-crate/blob/main/logsheets/transformed/sediment_measured.csv the sediment_temp 14999 should be corrected to 14.999

@melinalou

**Comment by melinalou** [comment]
it is already corrected

**Comment by cpavloud** [comment]
Please check also all the temperature values, there should be more cases. 
And also, remember to make the changes in the google spreadsheets too.

**Comment by melinalou** [comment]
it is checked and the changes are updated immediately in the https://drive.google.com/drive/folders/1kJXi46_8TydJuxb8Ltbd5eLOW1aUKIc3
