### ISSUE TITLE
Wrong dissolved oxygen values

### ISSUE THREAD

**Issue by cpavloud** [emo-bon/observatory-nrmcb-crate#13]
In https://github.com/emo-bon/observatory-nrmcb-crate/blob/main/logsheets/transformed/sediment_measured.csv the values of diss_oxygen 4741 should be corrected to 4.741

@melinalou

**Comment by melinalou** [comment]
already corrected

**Comment by cpavloud** [comment]
Please check also all the values, there should be more cases. 
And also, remember to make the changes in the google spreadsheets too.

**Comment by melinalou** [comment]
done. confirmed
