### ISSUE TITLE
Wrong pigments values

### ISSUE THREAD

**Issue by cpavloud** [emo-bon/observatory-nrmcb-crate#14]
In https://github.com/emo-bon/observatory-nrmcb-crate/blob/main/logsheets/transformed/sediment_measured.csv the pigments column has values with comma (e.g. 0,5523). They should be corrected to the correct decimal point (.)

@melinalou

**Comment by melinalou** [comment]
in the data i am looking to it is already replaced with (.)
https://docs.google.com/spreadsheets/d/1a19q3w2sP7dae8HEzT5TdmfqhRQQd3GItFqiYxWJlxs/edit?gid=15718907#gid=15718907

**Comment by cpavloud** [comment]
Ok.
Then maybe when the google spreadsheets need to be re-harvested so that the changes appear in the .csv files too.
